name: van_events_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.1
  firebase_auth: ^0.18.3+1
  firebase_storage: ^5.1.0
  cloud_firestore: ^0.14.3+1
  google_sign_in: ^4.5.6
  auto_route: ^0.6.9
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.2+1
  firebase_analytics: ^6.2.0
  image_picker: ^0.6.7+14
  font_awesome_flutter: ^8.10.0
  flare_flutter: ^2.0.6
  curved_navigation_bar: ^0.3.4
  flutter_progress_button: ^1.0.0
  flutter_swiper: ^1.1.6
  flutter_local_notifications: ^3.0.1+6
  flutter_circular_chart: ^0.1.0
  flutter_form_builder: ^4.0.2
  intl: ^0.16.1
  platform_alert_dialog: ^1.0.0+2
  cached_network_image: ^2.4.1
  photo_view: ^0.10.3
  giphy_picker: ^1.0.8
  badges: ^1.1.4
  async: ^2.4.2
  modal_progress_hud: ^0.1.3
  cloud_functions: ^0.7.1
  after_init: ^0.1.2
  flutter_stripe_payment: ^0.0.12
  qr_flutter: ^3.2.0
  flutter_slidable: ^0.5.7
  screen: ^0.0.5
  majascan: ^0.3.7
  pdf: ^1.12.0
  path_provider: ^1.6.24
  share_extend: ^1.1.9
  add_2_calendar: ^1.4.0
  map_launcher: ^1.0.0
  emoji_picker: ^0.1.0
  shimmer: ^1.1.2
  dio: ^3.0.10
  equatable: ^1.2.5
  after_layout: ^1.0.7+2
  multi_image_picker: ^4.7.14
  url_launcher: ^5.7.10
  flutter_chips_input: ^1.9.4
  google_maps_webservice: ^0.0.18
  flutter_google_places: ^0.2.6
  flutter_custom_dialog: ^1.0.20
  geolocator: ^6.1.9
  geoflutterfire: ^2.2.1
  google_maps_flutter: ^1.0.6
  flutter_polyline_points: ^0.2.4
  carousel_slider: ^2.3.1
  hooks_riverpod: ^0.12.1
  flutter_hooks: ^0.15.0
  paginate_firestore: ^0.2.2
  swipe_to: ^0.0.1+8
  flutter_launcher_icons: ^0.8.1
  flutter_bloc: ^6.1.1
  bloc: ^6.1.0

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
